spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/booklabs
    username: postgres
    password: adminadmin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate: 
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

# Get some info on requests to log
logging:
  level:
    org:
      springframework:
        web: INFO
        
wordservice:
  url:
    base: https://api.datamuse.com
    words: /words?ml=
