spring:
  main:
    banner-mode: off

# Get some info on requests to log
logging:
  level:
    org:
      springframework:
        web: DEBUG
        
wordservice:
  url:
    base: https://api.datamuse.com
    words: /words?ml=
